services:
  - type: web
    name: mydjtv-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        fromDatabase:
          name: mydjtv-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        fromService:
          type: web
          name: mydjtv-frontend
          property: url
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: VAPID_PUBLIC_KEY
        sync: false
      - key: VAPID_PRIVATE_KEY
        sync: false

  - type: web
    name: mydjtv-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: mydjtv-backend
          property: url
        suffix: /api
      - key: VITE_SOCKET_URL
        fromService:
          type: web
          name: mydjtv-backend
          property: url
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: VITE_VAPID_PUBLIC_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: VENUE_PASSWORD
        sync: false
      - key: USER_PASSWORD
        sync: false

databases:
  - name: mydjtv-db
    databaseName: mydjtv
    user: mydjtv