services:
  - type: web
    name: mydjtv-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mydjtv-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://mydjtv-frontend.onrender.com

  - type: web
    name: mydjtv-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://mydjtv-backend.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://mydjtv-backend.onrender.com

databases:
  - name: mydjtv-db
    databaseName: mydjtv
    user: mydjtv
    plan: free